/*
 * This source file was generated by the Gradle 'init' task
 */
package com.gustavsvensk.ordfyran.dictionaries;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
